### ISSUE TITLE
unclear how to execute the tests

### ISSUE THREAD

**Issue by nwsparks** [Devskiller/devskiller-sample-terraform-aws#1]
it's unclear what directory to execute `bats verify_tests.bats` from. based on the example provided here and how the tests need to be uploaded to devskiller none of the directories seem to actually work correctly and will report errors about files not found.

i'm wondering if there are some environments variables or something missing? would be nice to have more details overall for how to execute these when developing locally so that it matches what needs to be uploaded.

**Comment by kamil-olszewski-devskiller** [comment]
@nwsparks Noah, thank you for your feedback. We also received your information in the TalentScore chat and will be contacting you through this channel from this point onwards.
